### ISSUE TITLE
Improve error message when failing to parse rustdoc output

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-check#105]
Every so often, new Rust nightlies might cause the rustdoc JSON output format to change in a backward-incompatible way.

`cargo-semver-checks` will remain compatible with the most recent nightly's output, and we have a test that ensures that. However, users may still be using an older (or newer!) nightly that is incompatible with their `cargo-semver-checks` version.

If the JSON fails to parse, we should:
- check the nightly version to see if it's known to not work because it's too old (related: #88), then advise the user to upgrade to a newer nightly Rust
- otherwise, the nightly may be too new for the `cargo-semver-checks` version and we should advise the user to try upgrading to a newer `cargo-semver-checks` (as in #98)

**Comment by aDotInTheVoid** [comment]
The best way to do this is probably to check the `format_version` field, which is ment for this purpose.

Eg

https://github.com/awslabs/smithy-rs/blob/6b356c48591f5fdbfc73e2fcac11d0c932865582/tools/cargo-check-external-types/src/cargo.rs#L75-L97

**Comment by obi1kenobi** [comment]
Amazing, thanks!
