### ISSUE TITLE
Windows: failed when running cargo-doc; no such subcommand: `+nightly`

### ISSUE THREAD

**Issue by Bromeon** [obi1kenobi/cargo-semver-check#116]
### Steps to reproduce the bug with the above code

On Windows 10:
```bat
git clone https://github.com/Bromeon/js-sandbox.git
cd js-sandbox
cargo semver-checks check-release -p js-sandbox
```

### Actual Behaviour

```bat
cargo semver-checks check-release -p js-sandbox
    Updating index
     Parsing js-sandbox v0.2.0-rc.0 (current)
Error: Failed when running cargo-doc on <path>\js-sandbox\Cargo.toml: error: no such subcommand: `+nightly`
```

### Expected Behaviour

Getting output about semver compatibility, or at least a logic-related error.

### Additional Context

I tried with both cargo-semver-checks versions 0.9.1 and 0.9.2, same results.
I also tried alternative ways to invoke Cargo:
```rs
rustup run nightly cargo semver-checks check-release
    Updating index
     Parsing js-sandbox v0.2.0-rc.0 (current)
Error: Failed when running cargo-doc on <path>\js-sandbox\Cargo.toml: error: no such subcommand: `+nightly`

        Cargo does not handle `+toolchain` directives.
        Did you mean to invoke `cargo` through `rustup` instead?
```

It works when I run it on WSL2 (Linux) from the same Windows machine.

#### Software version

cargo-semver-checks 0.9.2

#### Operating system

Windows 6.2.9200

#### Command-line

```bash
C:\Users\<me>\.cargo\bin\cargo-semver-checks.exe semver-checks check-release -p js-sandbox --bugreport
```

#### cargo nightly version

```
> cargo +nightly -V
cargo 1.65.0-nightly (6da726708 2022-08-23)
```

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

**Comment by epage** [comment]
rustup changed how it resolves things in [1.25.0](https://blog.rust-lang.org/2022/07/11/Rustup-1.25.0.html) which broke a lot of programs.  It reverted the change in [1.25.1](https://blog.rust-lang.org/2022/07/12/Rustup-1.25.1.html) but it seems like some of the behavior is still lingering around on windows.

**Comment by epage** [comment]
Ah, looks like there is an issue: https://github.com/rust-lang/rustup/issues/3036

**Comment by Bromeon** [comment]
Wow, thanks for the instant response! 🚀

That's unfortunate, but at least good to hear it's a known issue. Might then need to wait until rustup resolves this...

In the meantime, I might play around with the CI a bit. The GitHub Action seems to have no option to specify the base version, right? Let's say I'm working on v1.7 and want to check compatibility with v1.6, but v2.2 has already been released -- will that infer v1.7 from the current `Cargo.toml` and compare it automatically against the next-lower crates.io release? Or what's the behavior exactly?

**Comment by epage** [comment]
> Let's say I'm working on v1.7 and want to check compatibility with v1.6, but v2.2 has already been released -- will that infer v1.7 from the current Cargo.toml and compare it automatically against the next-lower crates.io release? Or what's the behavior exactly?

I do not recall, but we should probably update the action to using recently introduced built-in logic rather than re-implementing it all in bash.

Another change the action should probably do after that is to pass in the `--workspace` flag.  We already will automatically ignore `publish = false` crates, so we'll probably be generally safe to use it in CI.

**Comment by obi1kenobi** [comment]
> Let's say I'm working on v1.7 and want to check compatibility with v1.6, but v2.2 has already been released -- will that infer v1.7 from the current `Cargo.toml` and compare it automatically against the next-lower crates.io release?

Yes — the action will compare to the maximum release smaller than the current version. I believe there's an edge case around pre-release versions (it might compare pre-releases to each other instead of comparing both to the prior stable version) but for your example it should work fine.

@epage agreed on switching to the new logic now that we have it 👍

**Comment by loafofpiecrust** [comment]
I also have this issue when installing rust directly through nix, since it doesn't involve rustup at all. Would it be possible to check if cargo is run through rustup before using the `+nightly` flag? I figure then I'll have to use nightly for my rust install, which is okay with me.

**Comment by epage** [comment]
Another option is for us to switch to stable via `RUSTC_BOOTSTRAP`.
