### ISSUE TITLE
Mutually exclusive features

### ISSUE THREAD

**Issue by thvdveld** [obi1kenobi/cargo-semver-check#134]
Is there a reason why the all-features flag is passed? In some rare cases, features are mutually exclusive (for example in `smoltcp`) and therefore it's unable to use `cargo-semver-check`.

https://github.com/obi1kenobi/cargo-semver-check/blob/423444100fe09adde0d621a730fec01681fc1387/src/dump.rs#L79

**Comment by epage** [comment]
Reasons
- We have not designed the configuration around this
- One factor for designing config is that I'm hoping we can find a way to track conditional compilation and find breaking changes via feature changes.  Knowing what direction we can go on this will have on impact on the design for configuring features.
- Everything is generally a safe default for capturing the whole API
- Mutually exclusive features are themselves not an officially supported use case within `cargo`, see https://github.com/rust-lang/cargo/issues/2980

**Comment by thvdveld** [comment]
Thank you for the explanation!

**Comment by thvdveld** [comment]
Using `--default-features` seems to work as expected. Thank you for the notification!
