### ISSUE TITLE
Wrong path to generated rustdoc when giving a manifest path

### ISSUE THREAD

**Issue by tonowak** [obi1kenobi/cargo-semver-check#174]
### Steps to reproduce the bug with the above code

Run `cargo run semver-checks check-release --manifest-path="../rust-libp2p/Cargo.toml"` on rust-libp2p from github

### Actual Behaviour

```
Error: Could not find expected rustdoc output for `libp2p`: ../rust-libp2p/target/semver-checks/registry-libp2p-0_49_0/target/semver-checks/target/doc/rustdoc.json
```

### Expected Behaviour

It should search for libp2p.json instead of rustdoc.json

#### Software version

cargo-semver-checks 0.12.1

#### Operating system

Linux 6.0.6-arch1-1

#### Command-line

```bash
/home/tonowak/.cargo/bin/cargo-semver-checks semver-checks --bugreport
```

#### cargo nightly version

```
> cargo +nightly -V
cargo 1.67.0-nightly (9286a1beb 2022-11-04)
```

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,llvm14-builtins-abi,sse,sse2
- Host: x86_64-unknown-linux-gnu

### Additional Context

https://github.com/obi1kenobi/cargo-semver-check/commit/fb3b8651ce70dc23f944ccec3b34125325a48ec3#diff-287794009d29d730666bc52a753aa89762117c87581cf348cc9b38def528ffcbR105
This seems to be the issue.

Fixing this will help with merging https://github.com/obi1kenobi/cargo-semver-check/pull/173

**Comment by tonowak** [comment]
Do you think that when you'll fix this bug @obi1kenobi ? It would make testing https://github.com/obi1kenobi/cargo-semver-check/pull/173 easier (especially when we're considering adding a GitHub Action, so I cannot just locally revert changes from the problematic commit).

**Comment by obi1kenobi** [comment]
I'm looking at it right now. If it doesn't end up being quickly fixable then we should just revert my earlier PR that introduced the problem, and test & merge #173 instead.

**Comment by tonowak** [comment]
It searches for `libp2p-core.json`, but in the folder I've found `libp2p_core.json`.

**Comment by obi1kenobi** [comment]
Ah, right. I forgot about that. Sorry!

All these are great example commands to attempt and ensure work correctly if we're adding the integration tests we were chatting about in https://github.com/obi1kenobi/cargo-semver-check/pull/173#issuecomment-1308991297 btw! Thanks for mentioning them explicitly so we can add them more easily.
