### ISSUE TITLE
Trait impls missing when generating rustdoc JSON without `--document-private-items` flag

### ISSUE THREAD

**Issue by obi1kenobi** [obi1kenobi/cargo-semver-check#32]
For unknown reasons, rustdoc JSON output sometimes does not include information about all the traits implemented by a type unless `--document-private-items` is specified. For example, in this `clap` [semver regression](https://github.com/clap-rs/clap/issues/3876):
- The following invocation on v3.1.18 generates JSON stating that `UnwindSafe` is implemented for `ArgMatches`: `cargo rustdoc --lib --all-features -- --document-private-items -Zunstable-options --output-format json`
- However, the following invocation has no mention of `UnwindSafe` for `ArgMatches` at all: `cargo rustdoc --lib --all-features -- -Zunstable-options --output-format json`

It's unclear to me at the moment whether this is expected behavior from rustdoc, or a bug. Will triage and use this as a tracking issue.

In the meantime:
- [x] the docs should recommend `--document-private-items` and `--all-features` in the rustdoc invocation
- [x] the GitHub Action should use both of these flags by default

**Comment by camelid** [comment]
Hi, I work on rustdoc, although I'm not super familiar with the JSON backend. This sounds like a bug to me since the `UnwindSafe` impl is public API. Can you open an issue for this at rust-lang/rust?

**Comment by obi1kenobi** [comment]
I believe this was fixed upstream on one of the more recent nightlies. Closing for now, willing to reopen if we find more regressions. Having `--document-private-items` probably makes the checking a bit slower but probably not meaningfully so, and we can revisit whether we add it by default when the JSON format is closer to stabilization.
